ToDoEU/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoEU.Models.Domain;
using ToDoEU.Models.DTO;

namespace ToDoEU.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ToDoDbContext _db;
        private readonly string? _userId;
        public AdminController(ToDoDbContext db)
        {
            _db = db;
            _userId = Environment.UserName;
        }
        public IActionResult Display()
        {
            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                {
                    return NotFound();
                }
                return View(toDoList);
            }
        }
        public IActionResult DisplayAdmin()
        {

            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                    return NotFound();
                return View(toDoList);
            }
        }
        //GET
        public IActionResult Delete(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteToDo(int? itemId)
        {
            ToDoItemModel? toDoObj = _db.ToDoItems.Find(itemId.Value);
            if (toDoObj == null)
            {
                return NotFound();
            }

            _db.ToDoItems.Remove(toDoObj);
            _db.SaveChanges();
            TempData["success"] = "ToDo Goal successfully deleted";
            return RedirectToAction("DisplayAdmin");
        }
    }
}

ToDoEU/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoEU.Models.Domain;
using ToDoEU.Models.DTO;

namespace ToDoEU.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ToDoDbContext _db;
        private string? _userId;
        public DashboardController(ToDoDbContext db)
        {
            _db = db;
            _userId = Environment.UserName;
        }
        public IActionResult Display()
        {
            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                {
                    return NotFound();
                }
                return View(toDoList);
            }
        }
        public IActionResult Create(string name)
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoItemModel toDoObj)
        {
            if (toDoObj.ItemName == toDoObj.ItemDescription.ToString())
            {
                ModelState.AddModelError("name", "ToDo Name cannot exactly match the Description.");
            }
            if (toDoObj.ItemName != null && toDoObj.ItemDescription.ToString() != null)
            {
                //Guid myuuid = Guid.NewGuid();
                //string todoItemId = myuuid.ToString();
                // Don't forget to insert email from form
                //toDoObj.ItemId = todoItemId;
                toDoObj.userId = User.Identity.Name;
                toDoObj.ItemStatus = "pending";
                _db.ToDoItems.Add(toDoObj);
                _db.SaveChanges();
                TempData["success"] = "ToDo Goal successfully created";
                return RedirectToAction("Display");
            }
            else
            {
                return View(toDoObj);
            }
        }

        //GET
        public IActionResult Edit(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoItemModel toDoObj)
        {
            if (toDoObj.ItemName == toDoObj.ItemDescription.ToString())
            {
                ModelState.AddModelError("name", "Display Order cannot exactly match the Name.");
            }
            if (toDoObj.ItemName != "" && toDoObj.ItemDescription.ToString() != "")
            {
                _db.ToDoItems.Update(toDoObj);
                _db.SaveChanges();
                TempData["success"] = "ToDo Goal successfully updated";
                return RedirectToAction("Display");
            }
            return View(toDoObj);
        }
        //GET
        public IActionResult Delete(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteToDo(int? itemId)
        {
            ToDoItemModel? toDoObj = _db.ToDoItems.Find(itemId.Value);
            if (toDoObj == null)
            {
                return NotFound();
            }

            _db.ToDoItems.Remove(toDoObj);
            _db.SaveChanges();
            TempData["success"] = "ToDo Goal successfully deleted";
            return RedirectToAction("Display");
        }
    }
}

ToDoEU/Controllers/UserAuthenticationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ToDoEU.Models.DTO;
using ToDoEU.Respository.Abstract;

namespace ToDoEU.Controllers
{
    public class UserAuthenticationController : Controller
    {
        private readonly IUserAuthenticationService _service;
        public UserAuthenticationController(IUserAuthenticationService service)
        {
            this._service = service;
        }

        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationModel model)
        {
            if(!ModelState.IsValid)
                return View(model);
            model.Role = "user";
            var result = await _service.RegistrationAysnc(model);
            TempData["msg"] = result.Message;
            return RedirectToAction(nameof(Registration));
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await _service.LoginAysnc(model);
            if (result.StatusCode == 1)
            {
                return RedirectToAction("Display", "Dashboard", model); ;
            }
            else
            {
                TempData["msg"] = result.Message;
                return RedirectToAction(nameof(Login));
            }

        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _service.LogoutAsync();
            return RedirectToAction(nameof(Login));
        }

        //public async Task<IActionResult> Reg()
        //{
        //    var model = new RegistrationModel()
        //    {
        //        Username = "admin",
        //        Name = "Ext_todo_admin",
        //        Email = "joshua.oguntola22@gmail.com",
        //        Password = "Admin@123456",
        //    };
        //    model.Role = "admin";
        //    var result = await _service.RegistrationAysnc(model);
        //    return Ok(result);
        //}
    }
}

ToDoEU/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/journalTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoEU.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" >ToDoEU</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Display">Dashboard</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="DisplayAdmin">Admin</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserAuthentication" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<!-- Client side Validation -->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_Notification" />
    }
}

ToDoEU/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.success('@TempData["success"]')
        </script>
}
@if (TempData["error"] != null)
{
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
        <script type="text/javascript">
            toastr.error('@TempData["success"]')
        </script>
}