ToDoEU/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ToDoEU.Models.Domain;
using ToDoEU.Models.DTO;

namespace ToDoEU.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ToDoDbContext _db;
        private readonly string? _userId;
        public AdminController(ToDoDbContext db)
        {
            _db = db;
            _userId = Environment.UserName;
        }
        public IActionResult Display()
        {
            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                {
                    return NotFound();
                }
                return View(toDoList);
            }
        }
        public IActionResult DisplayAdmin()
        {

            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                    return NotFound();
                return View(toDoList);
            }
        }
        //GET
        public IActionResult Delete(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteToDo(int? itemId)
        {
            ToDoItemModel? toDoObj = _db.ToDoItems.Find(itemId.Value);
            if (toDoObj == null)
            {
                return NotFound();
            }

            _db.ToDoItems.Remove(toDoObj);
            _db.SaveChanges();
            TempData["success"] = "ToDo Goal successfully deleted";
            return RedirectToAction("DisplayAdmin");
        }
    }
}

ToDoEU/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ToDoEU.Models.Domain;
using ToDoEU.Models.DTO;

namespace ToDoEU.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ToDoDbContext _db;
        private string? _userId;
        public DashboardController(ToDoDbContext db)
        {
            _db = db;
            _userId = Environment.UserName;
        }
        public IActionResult Display()
        {
            if (_userId == null)
            {
                return NotFound();
            }
            else
            {
                IEnumerable<ToDoItemModel> toDoList = _db.ToDoItems.ToList();
                if (toDoList == null)
                {
                    return NotFound();
                }
                return View(toDoList);
            }
        }
        public IActionResult Create(string name)
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ToDoItemModel toDoObj)
        {
            if (toDoObj.ItemName == toDoObj.ItemDescription.ToString())
            {
                ModelState.AddModelError("name", "ToDo Name cannot exactly match the Description.");
            }
            if (toDoObj.ItemName != null && toDoObj.ItemDescription.ToString() != null)
            {
                //Guid myuuid = Guid.NewGuid();
                //string todoItemId = myuuid.ToString();
                // Don't forget to insert email from form
                //toDoObj.ItemId = todoItemId;
                toDoObj.userId = User.Identity.Name;
                toDoObj.ItemStatus = "pending";
                _db.ToDoItems.Add(toDoObj);
                _db.SaveChanges();
                TempData["success"] = "ToDo Goal successfully created";
                return RedirectToAction("Display");
            }
            else
            {
                return View(toDoObj);
            }
        }

        //GET
        public IActionResult Edit(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ToDoItemModel toDoObj)
        {
            if (toDoObj.ItemName == toDoObj.ItemDescription.ToString())
            {
                ModelState.AddModelError("name", "Display Order cannot exactly match the Name.");
            }
            if (toDoObj.ItemName != "" && toDoObj.ItemDescription.ToString() != "")
            {
                _db.ToDoItems.Update(toDoObj);
                _db.SaveChanges();
                TempData["success"] = "ToDo Goal successfully updated";
                return RedirectToAction("Display");
            }
            return View(toDoObj);
        }
        //GET
        public IActionResult Delete(int? itemId)
        {
            if (!itemId.HasValue)
            {
                return NotFound();
            }
            var toDoFromDb = _db.ToDoItems.Find(itemId.Value);
            //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id);
            //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

            if (toDoFromDb == null)
            {
                return NotFound();
            }
            return View(toDoFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteToDo(int? itemId)
        {
            ToDoItemModel? toDoObj = _db.ToDoItems.Find(itemId.Value);
            if (toDoObj == null)
            {
                return NotFound();
            }

            _db.ToDoItems.Remove(toDoObj);
            _db.SaveChanges();
            TempData["success"] = "ToDo Goal successfully deleted";
            return RedirectToAction("Display");
        }
    }
}

ToDoEU/Views/Admin/Delete.cshtml
@model ToDoEU.Models.DTO.ToDoItemModel
@{
    ViewData["Title"] = "Delete Goal";
}

<form method="post" asp-action="Delete">
    <input asp-for="ItemId" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr />
        </div>
        <!-- <div asp-validation-summary="All"></div> -->
        <div class="mb-3">
            <label asp-for="ItemName"></label>
            <input asp-for="ItemName" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ItemDescription"></label>
            <input asp-for="ItemDescription" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ItemStatus"></label>
            <input asp-for="ItemStatus" class="form-control" disabled/>
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Admin" asp-action="DeleteAdmin" class="btn btn-secondary" style="width:150px">
            Back to Admin
        </a>
    </div>
</form>

<!-- Client side Validation -->
@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
        <partial name="_Notification" />
    }
}

ToDoEU/Views/Admin/Display.cshtml
@model IEnumerable<ToDoEU.Models.DTO.ToDoItemModel>
@{
    var name = User.Identity.Name;
    ViewData["Title"] = "Admin Dashboard";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">TODO List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Dashboard" asp-action="Create" class="btn btn-primary" asp-route-name="@name">
                <i class="bi bi-plus-circle"></i>&nbsp; Create New Goal
            </a>
        </div>
    </div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>ToDo Activity</th>
            <th>Discription</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
            @foreach (var obj in Model)
            {
                @if (obj.userId == name)
                {
                  <tr>
                  <td width="30%">
                    @obj.ItemName
                  </td>
                  <td width="30%">
                    @obj.ItemDescription
                  </td>
                  <td width="20%">
                    @obj.ItemStatus
                  </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                        <a asp-controller="Dashboard" asp-action="Edit" asp-route-ItemId="@obj.ItemId" class="text-success">
                            <i class="bi bi-pencil-square"></i> Edit
                        </a>|
                        <a asp-controller="Dashboard" asp-action="Delete" asp-route-ItemId="@obj.ItemId" class="text-danger">
                            <i class="bi bi-trash3"></i> Delete
                        </a>
                        </div>
                    </td>
                  </tr>
                }
            }
    </tbody>
</table>
</div>

ToDoEU/Views/Admin/DisplayAdmin.cshtml
@model IEnumerable<ToDoEU.Models.DTO.ToDoItemModel>
@{
    ViewData["Title"] = "Admin Dashboard";
}
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">TODO Admin List</h2>
        </div>
    </div>
    <br /><br />

<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>ToDo Activity</th>
            <th>Discription</th>
            <th>Status</th>
            <th>User</th>
        </tr>
    </thead>
    <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="30%">
                    @obj.ItemName
                    </td>
                    <td width="30%">
                    @obj.ItemDescription
                    </td>
                    <td width="20%">
                        @obj.ItemStatus
                    </td>
                    <td width="20%">
                        @obj.userId
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Admin" asp-action="Delete" asp-route-ItemId="@obj.ItemId" class="text-danger">
                                <i class="bi bi-trash3"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
    </tbody>
</table>
</div>